# -*- coding: utf-8 -*-
"""image_compressor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gA6ju-N3ZFNtrkms-y6208eJ4HgByfeO
"""

import pandas as pd
import numpy as np
from skimage.io import imread, imshow
image = imread('dog.jpg', as_gray=True)
image.shape

import cv2

import matplotlib.pyplot as plt

plt.imshow(image, cmap='gray')
plt.show

mini = min(image.shape)
son = 0
n = 0
while(2**n<=mini):
  n = n+1
n = n - 1
print(2**(n))

a,b = image.shape
if a%2!=0:
  image =np.concatenate((image,np.zeros((1,b))),axis=0)
  a = a+1
if b%2!=0:
  image = np.concatenate((image,np.zeros((a,1))),axis=1)

a,b = image.shape
list1 = []
list2 = []
list1.extend(list(range(int((a-2**n)/2))))
list1.extend(list(range(a-int((a-2**n)/2),a)))
list2.extend(list(range(int((b-2**n)/2))))
list2.extend(list(range(b-int((b-2**n)/2),b)))
image = (np.delete(image,list1,axis=0))
image = (np.delete(image,list2,axis=1))

image.shape

plt.imshow(image, cmap='gray')
plt.show()

image[:2,:2]

a,b  = image.shape
c = 0
narr = np.zeros((a,a))
for i in range(int(a/2)):
   narr[:,i] = (image[:,c]+image[:,c+1])/2
   narr[:,int(a/2)+i] = (image[:,c]-image[:,c+1])/2
   c = c+2
print(narr)

(narr[0,:] - narr[1,:])/2

c = 0
a,b = image.shape
narr2 = np.zeros((a,a))
for i in range(int(a/2)):
  narr2[i,: ] = (narr[c,:]+narr[c+1,:])/2
  narr2[int(a/2)+i,:] = (narr[c,:]-narr[c+1,:])/2
  c = c+2
narr2

import matplotlib.pyplot as plt
import numpy as np

import PIL.Image as Image

plt.imshow(narr2, cmap='gray')
plt.show()

from PIL import Image
import numpy as np

# Rasm o'lchamlari
width = 4
height = 4

# Rasm ma'lumotlari
image_data = [
    [255, 0, 255, 0],
    [0, 255, 0, 255],
    [255, 0, 255, 0],
    [0, 255, 0, 255]
]

# Numpy massiviga aylantirish
image_array = np.array(image_data, dtype=np.uint8)

# PIL rasm obyektini yaratish
image = Image.fromarray(image_array)

# Rasmni chiqarish
image.show()

